#!/bin/bash
#
# Much simpler than the earlier version, but needs at least v0.16.0 of Neovide.
#
if [[ "$*" =~ ^[^\ ]+:[0-9]+$ ]] ; then
  args="+${*#*:} ${*%:*}"
else
  args="$@"
fi
open -n -a Neovide --args --no-tabs --reuse-instance --chdir "$PWD" $args
