#!/bin/bash
# only handle line number if argument is a single file
if [[ "$*" =~ ^[^\ ]+:[0-9]+$ ]] ; then
  # ignore column number if we get eg path/to/file:123:45
  IFS=: read -r file line _ <<< "$*"
  args="+$line $file"
else
  args="$@"
fi
open -n -a Neovide --args --no-tabs --reuse-instance --chdir "$PWD" $args
